/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCajero;

import ControladorCajero.ListaDeUsuariosCjero;
import ModeloCajero.UsuarioCajero;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author elian
 */
public class JFrameRegistro extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRegistro
     */
    public JFrameRegistro() {
        initComponents();
        this.setResizable(false);//redimensionar
        setLocationRelativeTo(this);//centar
        this.setTitle("Banca");
    }

    /**
     * Metodo que limpia los txt, y lo posiciona en la promer cahja de texto
     */
    public void limpiar() {
        txtUsuario2.setText("");
        txtcorreo2.setText("");
        txtcontra.setText("");
        txtUsuario2.requestFocus();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtcorreo2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtContraseña2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario2 = new javax.swing.JTextField();
        btnRgistrar3 = new javax.swing.JButton();
        btnlogue2 = new javax.swing.JButton();
        btbcerrar2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtcontra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CORREO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 95, -1));
        jPanel1.add(txtcorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, -1));
        jPanel1.add(txtContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 928, 152, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONTRASEÑA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 110, -1));
        jPanel1.add(txtUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 150, -1));

        btnRgistrar3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnRgistrar3.setText("REGISTRAR USUARIO");
        btnRgistrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRgistrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRgistrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        btnlogue2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnlogue2.setText("LOGUEARSE");
        btnlogue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogueActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1306, 844, 160, -1));

        btbcerrar2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btbcerrar2.setText("CERRAR");
        btbcerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbcerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btbcerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 113, -1));

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1471, 762, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("BIENVENIDOS AL SISTEMA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 310, 47));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaCajero/log-in-g639cfa011_640.jpg"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 332));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 338, 712, 25));
        jPanel1.add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbcerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btbcerrarActionPerformed

    private void btnlogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogueActionPerformed
        JFrameLogueo logue = new JFrameLogueo();

        logue.setVisible(true);
    }//GEN-LAST:event_btnlogueActionPerformed

    private void btnRgistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRgistrar1ActionPerformed
        try {
            if (txtUsuario2.getText().equals("")|| txtcorreo2.getText().equals("")||txtcontra.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "DEBES LLENAR LOS DATOS", "ERROR", JOptionPane.ERROR_MESSAGE); 
            } else {
                   String usu = txtUsuario2.getText();
        String correo = txtcorreo2.getText();
        String clave = txtcontra.getText();
        UsuarioCajero obj = new UsuarioCajero();
        ListaDeUsuariosCjero obj1 = new ListaDeUsuariosCjero();
        if (ListaDeUsuariosCjero.verificarUsuarioNuevo(usu) == -1) {
            obj.setNombre(usu);
            obj.setCorreo(correo);
            obj.setContraseña(clave);
            ListaDeUsuariosCjero.agregar(obj);
            JOptionPane.showMessageDialog(rootPane, "EL USUARIO SE REGISTRO CORRECTAMENTE");
            limpiar();
             JOptionPane.showMessageDialog(rootPane, "INGRESE CON SU USUARIO Y CONTRASEÑA");
            JFrameLogueo logue = new JFrameLogueo();
            logue.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "EL USUARIO YA EXISTE", "ERROR", JOptionPane.WARNING_MESSAGE);
            limpiar();
        }
            }
          
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_btnRgistrar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbcerrar2;
    private javax.swing.JButton btnRgistrar3;
    private javax.swing.JButton btnlogue2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtContraseña2;
    private javax.swing.JTextField txtUsuario2;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtcorreo2;
    // End of variables declaration//GEN-END:variables
}
