/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCajero;

import ControladorCajero.ListaDeUsuariosCjero;
import ModeloCajero.UsuarioCajero;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author elian
 */
public class JFrameLogueo extends javax.swing.JFrame {

    /**
     * Creates new form JFrameLogueo
     */
    public JFrameLogueo() {
        initComponents();
        this.setResizable(false);//redimensionar
        setLocationRelativeTo(this);//centar
       
    }

    /**
     * Metodo que limpia los txt, y lo posiciona en la promer caja de texto.
     */
    public void limpiar() {
        txtUsuario2.setText("");
        txtcontra.setText("");
        txtUsuario2.requestFocus();
    }
   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtContraseña2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario2 = new javax.swing.JTextField();
        btnlogue2 = new javax.swing.JButton();
        btbcerrar2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtcontra = new javax.swing.JPasswordField();
        btnRgistrar = new javax.swing.JButton();
        btblogueo = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, -1));
        jPanel2.add(txtContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 928, 152, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONTRASEÑA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 110, -1));
        jPanel2.add(txtUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 150, -1));

        btnlogue2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnlogue2.setText("LOGUEARSE");
        btnlogue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogue2btnlogueActionPerformed(evt);
            }
        });
        jPanel2.add(btnlogue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1306, 844, 160, -1));

        btbcerrar2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btbcerrar2.setText("CERRAR");
        btbcerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbcerrar2btbcerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btbcerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 113, -1));

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1471, 762, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("BIENVENIDOS AL SISTEMA");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 310, 47));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaCajero/log-in-g639cfa011_640.jpg"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 330));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 338, 712, 25));
        jPanel2.add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 160, -1));

        btnRgistrar.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnRgistrar.setText("REGISTRARSE");
        btnRgistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRgistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRgistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, 30));

        btblogueo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btblogueo.setText("LOGUEARSE");
        btblogueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btblogueoActionPerformed(evt);
            }
        });
        jPanel2.add(btblogueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogue2btnlogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogue2btnlogueActionPerformed
        JFrameLogueo logue = new JFrameLogueo();
        logue.setVisible(true);
    }//GEN-LAST:event_btnlogue2btnlogueActionPerformed

    private void btbcerrar2btbcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbcerrar2btbcerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btbcerrar2btbcerrarActionPerformed

    private void btnRgistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRgistrarActionPerformed
        JFrameRegistro registro = new JFrameRegistro();
        this.dispose();
        registro.setVisible(true);
    }//GEN-LAST:event_btnRgistrarActionPerformed
/**
 * se validan los txt para que no queden vacios 
 * @param evt 
 */
    private void btblogueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btblogueoActionPerformed
        try {
             if (txtUsuario2.getText().equals("") || txtcontra.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DEBES LLENAR LOS DATOS", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else{
            String usuario = txtUsuario2.getText();
            String contra = txtcontra.getText();
            int pos = ListaDeUsuariosCjero.verificarlogueo(usuario, contra);
            if (pos == -1) {
                JOptionPane.showMessageDialog(rootPane, "USUARIO O CONTRASEÑA ERRONEA");
                JOptionPane.showMessageDialog(rootPane, "SI AUN NO ES USUARIO VAYA A LA OPCION DE REGISTRO", "", JOptionPane.PLAIN_MESSAGE);
                limpiar();
            } else {
                JFrameLogrado logrado = new JFrameLogrado();
                logrado.setVisible(true);
                this.setVisible(false);
            }
        }} catch (Exception e) {
        }

    }//GEN-LAST:event_btblogueoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbcerrar2;
    private javax.swing.JButton btblogueo;
    private javax.swing.JButton btnRgistrar;
    private javax.swing.JButton btnlogue2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtContraseña2;
    private javax.swing.JTextField txtUsuario2;
    private javax.swing.JPasswordField txtcontra;
    // End of variables declaration//GEN-END:variables
}
